name: Store readme in Drive
on:
  push: { branches: [main] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - name: Download files
        run: |
         ls -ahl
