# .github/workflows/main.yml
name: Main
on:
  push:
    branches:
      - 'main'

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          wget https://github.com/ranaraju3874/gdrive-upload-action/files/11958687/json-to-base64-converter.txt -o gdrive.txt

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: gdrive.txt
          name: gdrive.txt
          folderId: ${{ secrets.folderId }}
          credentials: ${{ secrets.credentials }}
          encoded: true
