# .github/workflows/main.yml
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          wget https://github.com/ranaraju3874/gdrive-upload-action/files/11958687/json-to-base64-converter.txt -o gdrive.txt

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "gdrive.txt"
          folderId: ${{ secrets.folderId }}
